### ISSUE TITLE
_git_jump_near:40: = not found

### ISSUE THREAD

**Issue by ldong** [wuxc/gitjump#3]
git n
_git_jump_near:40: = not found

**Comment by ldong** [comment]
git version 2.9.2

**Comment by ldong** [comment]
Switch from zsh to bash solved the problem, issue closed.

**Comment by ldong** [comment]
Is there a way to run this intelligently with zsh compatibility?

I found one useful reference here, http://stackoverflow.com/questions/9910966/how-to-tell-if-its-using-zsh-or-bash

**Comment by wuxc** [comment]
Thanks for the issue. I'm not familiar with zsh & may take some time to fix it. 
At the same time, PRs are welcomed.
