### ISSUE TITLE
git log 有日志，但是用git first就显示没有提交记录

### ISSUE THREAD

**Issue by monkindey** [wuxc/gitjump#4]
你好，在 **MacOS zsh**里面用git first命令并没有显示提交记录

**Comment by wuxc** [comment]
请问下输出内容是啥样子的呢？

**Comment by monkindey** [comment]
原文

> No more commits.

**Comment by wuxc** [comment]
1.看下当前在哪个提交 git show|head -n1
2.麻烦看下.git/jump_logfile 有多少内容，上面那个提交是不是最后一条

**Comment by wuxc** [comment]
https://gitter.im/gitjump/Lobby 在这聊吧 刚建了个
